name: Build and Deploy Vite Assets
on:
  push:
    branches:
      - main # Ganti dengan nama branch Anda jika bukan main

jobs:
  web-deploy:
    name: Deploy Assets
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv

    - name: Add Flux Credentials Loaded From ENV
      run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install NPM Packages & Build Vite
      run: |
        npm install
        npm run build

    - name: Sync Build Folder to Hostinger via FTP
      uses: Wandalen/wretry.action@v3
      with:
        action: SamKirkland/FTP-Deploy-Action@v4.3.5
        attempt_limit: 3
        attempt_delay: 15000
        with: |
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./public/build/
          server-dir: public_html/public/build/
